version: '3.8'

services:
  mi-postgres:
    image: postgres:16-alpine
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: professor-oak
      POSTGRES_PASSWORD: gottacatchthemall
      POSTGRES_DB: pokedex_database
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pokedex-api:
    build: .
    container_name: pokedex-api-dev
    restart: always
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mi-postgres:5432/pokedex_database
    depends_on:
      - mi-postgres

volumes:
  postgres_data:
