version: '3.8'

services:
  mi-postgres:
    image: postgres:16-alpine
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: admin           # Tu usuario de base de datos
      POSTGRES_PASSWORD: password123 # Tu contraseña
      POSTGRES_DB: mi_base_datos     # El nombre de la base de datos que creará por defecto
    ports:
      - "5444:5432"                  # Mapeo de puertos (Host:Contenedor)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volumen para persistencia de datos

volumes:
  postgres_data: